- name: install apache2 server
  apt:
     name: apache2
     state: present

- name: checkout latest code from github
  git: 
    repo: "{{ repo_url }}"
    dest: /var/www/html/
    clone: yes

- name: copy lavarel project
  shell: sudo mv /var/www/html/laravel-realworld-example-app /var/www/html/{{ vhost_name }}

- name: Change permission
  shell: sudo chgrp -R www-data /var/www/html/{{ vhost_name }}/

- name: Change permission
  shell: sudo chmod -R 775 /var/www/html/{{ vhost_name }}/storage

- name: Change permission
  shell: sudo chmod -R 775 /var/www/html/{{ vhost_name }}/bootstrap/cache
  
- name: Change permission
  shell: sudo chmod -R 775 /var/www/html/{{ vhost_name }}

# - name: Remove default apache vhost config from sites-enabled
#   file: name=/etc/apache2/sites-enabled/000-default.conf state=absent

# - name: copy .env-example to .env
#   shell: sudo cp /var/www/html/{{ vhost_name}}/.env-example /var/www/html/{{ vhost_name }}/.env



- name: Create apache vhosts for  domain
  template: 
    src: web.conf.j2 
    dest: "/etc/apache2/sites-available/{{ vhost_name }}.conf" 
    owner: www-data 
    group: www-data 
    mode: 0644

- name: Enable the Apache rewrite module
  command:  a2enmod rewrite

- name: Disable apache default host configuration 
  command: a2dissite 000-default.conf

- name: Activate the lavarel virtual host configuration
  command:  a2ensite {{ vhost_name }}.conf

  notify:
    - restart apache2