- name: Update Composer
  command: composer self-update --stable

- name: installs all composer lib
  command: sudo composer install --no-interaction
  args:
      chdir: /var/www/html/laravel

- name: Run the php artisan key generate
  ansible.builtin.shell: php artisan key:generate
  args:
        chdir: /var/www/html/laravel

- name: Run the php artisan config cache
  ansible.builtin.shell: php artisan config:cache
  args:
        chdir: /var/www/html/laravel

- name: Run the php artisan migrate fresh
  ansible.builtin.shell: php artisan migrate:fresh
  args:
        chdir: /var/www/html/laravel
- name: Run the php artisan migrate seed
  ansible.builtin.shell: php artisan migrate --seed
  args:
        chdir: /var/www/html/laravel