- name: Update system
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade System
  apt: upgrade=yes cache_valid_time=3600

- name: Install Php dependencies
  command: apt install software-properties-common -y

- name: Add repository
  command: add-apt-repository ppa:ondrej/php -y

- name: Update system
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade System
  apt: upgrade=yes cache_valid_time=3600

- name: Install PHP 8.1
  command: apt install -y php8.1

- name: Install php dependencies
  apt:
      pkg: "{{ item }}"
      state: present
      update_cache: yes
  with_items:
    - libapache2-mod-php
    - php
    - php8.1-common
    - php8.1-tokenizer
    - php8.1-bcmath
    - php8.1-opcache
    - php8.1-cli
    - php8.1-curl
    - php8.1-gd
    - php8.1-intl
    - php8.1-mbstring
    - php8.1-mysql
    - php8.1-pgsql
    - php8.1-xml
    - php8.1-zip
  become: true

  #- name: checkout latest code from github
  # command: git clone https://github.com/f1amy/laravel-realworld-example-app.git
- name: Clone the project repo
  git:
    repo: https://github.com/f1amy/laravel-realworld-example-app.git
    dest: /home/ubuntu/
    clone: yes
    update: no

- name: Checking if laravel-realworld-example exists
  stat:
     path: /home/ubuntu/laravel-realworld-example-app
  register: file_data
- name: Report if the directory exists
  debug:
    msg: "The directory exists"
  when: file_data.stat.exists
- name: Report Missing directory
  debug:
    msg: "The directory does not exist"
  when: not file_data.stat.exists

#- name: Move repo to web folder
#command: mv /home/ubuntu/laravel-realworld-example-app /var/www/html/

#- name: copy .env.example to .env
  #copy:
  # src: /var/www/html/laravel-realworld-example-app/.env.example
  # dest: /var/www/html/laravel-realworld-example-app/.env

#- name: copy lavarel project
# command: mv /var/www/html/laravel-realworld-example-app /var/www/html/laravel

- name: Change permission
  command: chgrp -R www-data /var/www/html/laravel/

- name: Change permission
  command: chgrp -R www-data /var/www/html/laravel/

- name: Change permission
  command: chmod -R 775 /var/www/html/laravel/storage

- name: Change permission
  command: chmod -R 775 /var/www/html/laravel/bootstrap/cache

- name: Change permission
  command: chmod -R 775 /var/www/html/laravel
- name: Copy .env.example to .env
  copy:
          dest: /var/www/html/laravel/.env
          group: root
          owner: root
          mode: 0755
          src: /var/www/html/laravel/.env.example

- name: Configure your .env file
  template: src=env.conf.j2 dest="/var/www/html/laravel/.env"
- name: Download Installer
  command: curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php

- name: Install
  command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

  #- name: rename composer.phar to composer
  #shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  #args:
  # creates: /usr/local/bin/composer
- name: Add Composer to global path
  copy:
          dest: /usr/local/bin/composer
          group: root
          owner: root
          mode: 0755
          src: /usr/local/bin/composer.phar
          remote_src: yes

- name: Update system
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade System
  apt: upgrade=yes cache_valid_time=3600

- name: make composer executable
  file:
    path: /usr/local/bin/composer
    mode: a+x
    state: file

# - name: Install a composer
#   ansible.builtin.apt:
#     name: composer
#     state: present
- name: Update system
  apt: update_cache=yes cache_valid_time=3600

  

