---

- name: Install essential packages to their latest version
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - git
    - vim
    - curl
    - ufw
    - wget
    - unzip
    - apache2
    - pip
  become: true

- name: Allow OpenSSH rule
  ufw:
    rule: allow
    name: OpenSSH
- name: Allow OpenSSH rule
  ufw:
    rule: allow
    name: 'WWW Full'